package com.tripflow.service;

import org.springframework.stereotype.Service;

import com.tripflow.kafka.messages.AIRequestMessage;
import com.tripflow.kafka.messages.NotificationMessage;

@Service
public class AIHandlerService {
    private final KafkaService kafkaService;

    public AIHandlerService(KafkaService kafkaService) {
        this.kafkaService = kafkaService;
    }

    public void handleAIRequest(AIRequestMessage request) {
        // Process the AI request TBD
        String message = "Your AI request has been processed.";
        String response = "Response generated by AI";

        System.out.println("Processed AI request for user: " + request.username());

        NotificationMessage notification = new NotificationMessage(request.username(), message, response);
        this.kafkaService.sendNotificationMessage(notification);
    }
}
