package com.tripflow.service;

import org.springframework.stereotype.Service;

import com.tripflow.kafka.messages.AIRequestMessage;
import com.tripflow.kafka.messages.NotificationMessage;

@Service
public class AIHandlerService {
    private final KafkaService kafkaService;
    private final AILogService aiLogService;

    public AIHandlerService(KafkaService kafkaService, AILogService aiLogService) {
        this.kafkaService = kafkaService;
        this.aiLogService = aiLogService;
    }

    public void handleAIRequest(AIRequestMessage request) {
        // Process the AI request TBD
        String message = "Your AI request has been processed.";
        String response = "Response generated by AI";

        this.aiLogService.saveAILog(request, response, true);

        NotificationMessage notification = new NotificationMessage(request.username(), message, response);
        this.kafkaService.sendNotificationMessage(notification);
    }
}
