name: CD - Publish Release

on:
  release:
    types: [published]

jobs:
  release-tag:
    uses: ./.github/workflows/cd-build.yaml
    with:
      tag: ${{ github.event.release.tag_name }}
      compose_file: docker/docker-compose.yaml
      services: '["backend/api-service","backend/ai-service","backend/notification-service","frontend"]'
    secrets: inherit

  release-latest:
    needs: release-tag
    uses: ./.github/workflows/cd-build.yaml
    with:
      tag: latest
      compose_file: docker/docker-compose.yaml
      services: '["backend/api-service","backend/ai-service","backend/notification-service","frontend"]'
    secrets: inherit

  trigger-dokploy:
    needs: release-latest
    if: ${{ secrets.DOKPLOY_URL != '' && secrets.DOKPLOY_AUTH_TOKEN != '' && secrets.DOKPLOY_COMPOSE_ID != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dokploy Deployment
        uses: benbristow/dokploy-deploy-action@0.2.2
        with:
          api_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_COMPOSE_ID }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          service_type: compose
